config/routes.rb
Rails.application.routes.draw do
  resources :gems, only: [:index]
  root to: "static_pages#root"
  get '/favorites' => "static_pages#favorites"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gems_controller.rb
class GemsController < ApplicationController
  def index
    @search_term = (params["gem"]["search_term"]).downcase
    @gem = find_gem(@search_term)
    if @gem.empty?
      flash.now[:errors] = "Oh no! Looks like that gem can't be found."
    else
      @search_term = ""
      dependencies = @gem['dependencies']
      @dependencies = dependencies["development"] + dependencies["runtime"]
    end
      render :index
  end

  private

  def find_gem(search_term)
    search_term = (params["gem"]["search_term"]).downcase
    begin
      gem = (Gems.info "#{@search_term}")
    rescue JSON::ParserError => error
      return {}
    end
    gem
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def root
  end

  def favorites
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gems_helper.rb
module GemsHelper
end

app/views/gems/index.html.erb
<div>
  <%= render "partials/search", search_term: @search_term %>
  <% unless flash[:errors] %>
    <div class="gem-details-container">
      <div id="gem-details" class="gem-details gem">
        <a href="https://rubygems.org/gems/<%= @gem["name"] %>"><%= @gem["name"] %></a>
        <button id="<%= @gem["name"] %>" class="toggle">
          <%= image_tag("star-gray.png") %>
        </button>
        <h3>INFORMATION</h3>
          <p><%= @gem["info"] %></p>
        <h3>DEPENDENCIES</h3>
          <% if @dependencies.empty? %>
            <p>None</p>
          <% else %>
            <ul>
              <% @dependencies.each do |dependency| %>
                <li>
                  <a href="https://rubygems.org/gems/<%= dependency["name"] %>"><%= dependency["name"] %></a>
                  <button id="<%= dependency["name"] %>" class="toggle">
                    <%= image_tag("star-gray.png") %>
                  </button>
                </li>
              <% end %>
              </ul>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FrontendTest</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="image-container">
    <div><%= image_tag("teachable-logo.png") %></div>
    <div class="links">
        <a id="search-link" href="/">Search</a>
        <a id="favorites-link" href="/favorites">Favorites</a>
    </div>
  </div>

<%= yield %>

</body>
</html>

app/views/partials/_search.html.erb
<% if flash[:errors] %>
  <% error = "error" %>
  <% text = flash[:errors] %>
<% else %>
  <% error = "" %>
  <% text = "" %>
<% end %>

<div class="search <%= error %>">
  <h1>Search Gems</h1>
  <form class= "" action="<%= gems_url %>" method="get">
    <input id="search_term" type="text" name="gem[search_term]" placeholder="Search" value="<%= search_term %>">
    <button>
      <%= image_tag("magnifying-glass.png") %>
    </button>
  </form>
  <h2>
    <%= text %>
  </h2>
</div>

app/views/static_pages/favorites.html.erb
<div class="favorites">
  <h1>Your Favorite Gems</h1>
  <ul id="favorites-list" class="gem">
  </ul>
</div>

app/views/static_pages/root.html.erb
<%= render "partials/search", search_term: "" %>